services:
  - type: web
    name: sequor
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        value: "postgresql://sequor_db_user:EJNle0qoQ8DqbxEgjGVwbyGVhdSZ6lum@dpg-d80vtd50lvsc739308f0-a/sequor_db"
      - key: JWT_SECRET
        value: "ccfa814c5c0eef94d4876d43d0ce6bd4d724613dab4addcf70c6d44ab8a5b666"
      - key: ENCRYPTION_MASTER_KEY
        value: "qP6dumbNwBfXIQ8z32PbK6sZTfcv39ELJzPSGZxKN/g="

databases:
  - name: sequor-db
    plan: free
