services:
  - type: web
    name: sequor
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: JWT_SECRET
        value: "ccfa814c5c0eef94d4876d43d0ce6bd4d724613dab4addcf70c6d44ab8a5b666"

databases:
  - name: sequor-db
    plan: free
