"""initial_schema

Revision ID: 5ab03308b1f3
Revises: 
Create Date: 2026-04-30 20:46:34.526785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '5ab03308b1f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'professional', 'enterprise', name='tenant_plan', create_constraint=True), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdpa_consent_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenants_email_domain', 'tenants', ['email_domain'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ownership_type', sa.Enum('individual', 'department', name='ownership_type', create_constraint=True), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('backup_contact_ids', sa.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('routing_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('escalation_sla_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='account_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_owner_email', 'accounts', ['owner_email'], unique=False)
    op.create_index('ix_accounts_status', 'accounts', ['status'], unique=False)
    op.create_index('ix_accounts_tenant_id', 'accounts', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_preference', sa.Enum('whatsapp', 'email', 'either', name='channel_preference', create_constraint=True), nullable=False),
    sa.Column('human_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    op.create_index('ix_contacts_tenant_id', 'contacts', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('faq', 'roster', 'price_list', 'policy', 'other', name='document_type', create_constraint=True), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'indexing', 'ready', 'stale', 'error', name='document_status', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    op.create_index('ix_documents_tenant_type', 'documents', ['tenant_id', 'type'], unique=False)
    op.create_table('backup_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.Enum('primary', 'second_tier', name='contact_tier', create_constraint=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_contacts_account_id', 'backup_contacts', ['account_id'], unique=False)
    op.create_index('ix_backup_contacts_tenant_id', 'backup_contacts', ['tenant_id'], unique=False)
    op.create_index('ix_backup_contacts_tier', 'backup_contacts', ['tier'], unique=False)
    op.create_table('channel_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', name='consent_channel', create_constraint=True), nullable=False),
    sa.Column('opt_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opt_in_method', sa.Enum('first_contact_notice', 'explicit_checkbox', 'verbal', name='opt_in_method', create_constraint=True), nullable=False),
    sa.Column('opt_in_notice_version', sa.String(length=50), nullable=True),
    sa.Column('opt_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_method', sa.Enum('replied_human', 'replied_stop', 'settings_change', name='withdrawal_method', create_constraint=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_consents_contact_channel', 'channel_consents', ['contact_id', 'channel'], unique=False)
    op.create_index('ix_channel_consents_contact_id', 'channel_consents', ['contact_id'], unique=False)
    op.create_index('ix_channel_consents_tenant_id', 'channel_consents', ['tenant_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_tenant_id', 'document_chunks', ['tenant_id'], unique=False)
    op.create_table('learned_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('human_answer', 'document', name='source_type', create_constraint=True), nullable=False),
    sa.Column('source_escalation_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learned_answers_account_id', 'learned_answers', ['account_id'], unique=False)
    op.create_index('ix_learned_answers_tenant_id', 'learned_answers', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction', create_constraint=True), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', name='message_channel', create_constraint=True), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('in_reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_raw', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whatsapp_session_expired', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['in_reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_contact_id', 'messages', ['contact_id'], unique=False)
    op.create_index('ix_messages_external_message_id', 'messages', ['external_message_id'], unique=False)
    op.create_index('ix_messages_received_at', 'messages', ['received_at'], unique=False)
    op.create_index('ix_messages_tenant_id', 'messages', ['tenant_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('doer_type', sa.Enum('ai_agent', 'backup_contact', 'user', 'system', name='doer_type', create_constraint=True), nullable=False),
    sa.Column('doer_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('recipient_type', sa.Enum('contact', 'backup_contact', 'user', 'system', name='recipient_type', create_constraint=True), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entries_doer', 'audit_entries', ['doer_type', 'doer_id'], unique=False)
    op.create_index('ix_audit_entries_occurred_at', 'audit_entries', ['occurred_at'], unique=False)
    op.create_index('ix_audit_entries_recipient', 'audit_entries', ['recipient_type', 'recipient_id'], unique=False)
    op.create_index('ix_audit_entries_tenant_id', 'audit_entries', ['tenant_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('classifier', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('routine', 'semi_routine', 'complex', 'high_stakes', name='classification_category', create_constraint=True), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='classification_urgency', create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classifications_message_id', 'classifications', ['message_id'], unique=False)
    op.create_index('ix_classifications_tenant_id', 'classifications', ['tenant_id'], unique=False)
    op.create_table('rag_retrievals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('document_ids', sa.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('passages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_confidence', sa.Float(), nullable=True),
    sa.Column('synthesis_confidence', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_retrievals_message_id', 'rag_retrievals', ['message_id'], unique=False)
    op.create_index('ix_rag_retrievals_tenant_id', 'rag_retrievals', ['tenant_id'], unique=False)
    op.create_table('routing_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('classification_category', sa.String(length=50), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('routing_target', sa.Enum('backup_contact', 'escalation_queue', 'auto_respond', 'primary_user', name='routing_target', create_constraint=True), nullable=False),
    sa.Column('backup_contact_id', sa.Uuid(), nullable=True),
    sa.Column('escalation_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('escalation_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=True),
    sa.Column('auto_response_accepted', sa.Boolean(), nullable=False),
    sa.Column('auto_response_rejected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backup_contact_id'], ['backup_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routing_outcomes_message_id', 'routing_outcomes', ['message_id'], unique=False)
    op.create_index('ix_routing_outcomes_routing_target', 'routing_outcomes', ['routing_target'], unique=False)
    op.create_index('ix_routing_outcomes_tenant_id', 'routing_outcomes', ['tenant_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('rag_retrieval_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_badge', sa.Enum('high', 'moderate', 'low', 'uncertain', name='confidence_badge', create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('was_auto_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backup_approver_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['backup_approver_id'], ['backup_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rag_retrieval_id'], ['rag_retrievals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responses_message_id', 'responses', ['message_id'], unique=False)
    op.create_index('ix_responses_tenant_id', 'responses', ['tenant_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=True),
    sa.Column('backup_contact_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'acknowledged', 'resolved', 'expired', name='escalation_status', create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='escalation_priority', create_constraint=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backup_contact_id'], ['backup_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escalations_assigned_at', 'escalations', ['assigned_at'], unique=False)
    op.create_index('ix_escalations_backup_contact_id', 'escalations', ['backup_contact_id'], unique=False)
    op.create_index('ix_escalations_message_id', 'escalations', ['message_id'], unique=False)
    op.create_index('ix_escalations_status', 'escalations', ['status'], unique=False)
    op.create_index('ix_escalations_tenant_id', 'escalations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_escalations_tenant_id', table_name='escalations')
    op.drop_index('ix_escalations_status', table_name='escalations')
    op.drop_index('ix_escalations_message_id', table_name='escalations')
    op.drop_index('ix_escalations_backup_contact_id', table_name='escalations')
    op.drop_index('ix_escalations_assigned_at', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('ix_responses_tenant_id', table_name='responses')
    op.drop_index('ix_responses_message_id', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_routing_outcomes_tenant_id', table_name='routing_outcomes')
    op.drop_index('ix_routing_outcomes_routing_target', table_name='routing_outcomes')
    op.drop_index('ix_routing_outcomes_message_id', table_name='routing_outcomes')
    op.drop_table('routing_outcomes')
    op.drop_index('ix_rag_retrievals_tenant_id', table_name='rag_retrievals')
    op.drop_index('ix_rag_retrievals_message_id', table_name='rag_retrievals')
    op.drop_table('rag_retrievals')
    op.drop_index('ix_classifications_tenant_id', table_name='classifications')
    op.drop_index('ix_classifications_message_id', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_audit_entries_tenant_id', table_name='audit_entries')
    op.drop_index('ix_audit_entries_recipient', table_name='audit_entries')
    op.drop_index('ix_audit_entries_occurred_at', table_name='audit_entries')
    op.drop_index('ix_audit_entries_doer', table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index('ix_messages_tenant_id', table_name='messages')
    op.drop_index('ix_messages_received_at', table_name='messages')
    op.drop_index('ix_messages_external_message_id', table_name='messages')
    op.drop_index('ix_messages_contact_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_learned_answers_tenant_id', table_name='learned_answers')
    op.drop_index('ix_learned_answers_account_id', table_name='learned_answers')
    op.drop_table('learned_answers')
    op.drop_index('ix_document_chunks_tenant_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_channel_consents_tenant_id', table_name='channel_consents')
    op.drop_index('ix_channel_consents_contact_id', table_name='channel_consents')
    op.drop_index('ix_channel_consents_contact_channel', table_name='channel_consents')
    op.drop_table('channel_consents')
    op.drop_index('ix_backup_contacts_tier', table_name='backup_contacts')
    op.drop_index('ix_backup_contacts_tenant_id', table_name='backup_contacts')
    op.drop_index('ix_backup_contacts_account_id', table_name='backup_contacts')
    op.drop_table('backup_contacts')
    op.drop_index('ix_documents_tenant_type', table_name='documents')
    op.drop_index('ix_documents_tenant_id', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_contacts_tenant_id', table_name='contacts')
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_accounts_tenant_id', table_name='accounts')
    op.drop_index('ix_accounts_status', table_name='accounts')
    op.drop_index('ix_accounts_owner_email', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_tenants_email_domain', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
